# Setup
title: Lunar Systematics
tagline: Research, Journalism, and Data Analytics
url: http://lunarsystematics.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-paginate

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

